whitelist_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_length
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nsobject_prefer_isequal
  - no_extension_access_modifier
  - no_space_in_method_call
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_boolean
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - static_operator
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_name
  - unneeded_break_in_switch
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

attributes:
  always_on_same_line:
    - '@IBAction'
    - '@IBOutlet'
    - '@IBDesignable'
    - '@IBInspectable'
    - '@GKInspectable'
    - '@NSCopying'
    - '@NSManaged'
    - '@dynamic'
    - '@nonobjc'
    - '@objc'
    - '@objcMembers'
    - '@testable'
  always_on_line_above:
    - '@UIApplicationMain'
    - '@NSApplicationMain'
    - '@dynamicMemberLookup'
    - '@dynamicCallable'
    - '@propertyWrapper'
    - '@convention'
    - '@frozen'
    - '@available'
    - '@discardableResult'
    - '@inlinable'
    - '@usableFromInline'
    - '@warn_unqualified_access'
    - '@requires_stored_property_inits'

closure_body_length: 20

colon:
  flexible_right_spacing: true
  apply_to_dictionaries: true

conditional_returns_on_newline:
  if_only: false

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true

deployment_target:
  iOS_deployment_target: '11.0'

discouraged_direct_init:
  types:
    - Bundle
    - UIDevice
    - AVAudioSession

discouraged_object_literal:
  image_literal: true
  color_literal: true

duplicate_enum_cases:
  severity: warning

dynamic_inline:
  severity: warning

file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: false

file_name:
  excluded:
    - main.swift
  prefix_pattern: ''
  suffix_pattern: '[+][A-z][A-z]+'
  nested_type_separator: '.'

function_body_length: 40

function_parameter_count: 5

generic_type_name:
  max_length: 20
  validates_start_with_lowercase: true

identifier_name:
  min_length: 3
  max_length: 40
  validates_start_with_lowercase: true
  excluded:
    - i
    - j
    - x
    - y
    - z
    - to
    - at
    - on
    - id
    - up
    - go
    - ok

large_tuple: 3

line_length: 120

modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - owned
    - mutators
    - final
    - typeMethods
    - required
    - convenience
    - lazy
    - dynamic

nesting:
  type_level: 4
  statement_level: 5

number_separator:
  minimum_length: 5
  minimum_fraction_length: 5
  exclude_ranges: []

overridden_super_call:
  included:
    - '*'
  excluded: []

private_outlet:
  allow_private_set: false

private_over_fileprivate:
  validate_extensions: true

prohibited_super_call:
  included:
    - '*'
  excluded: []

statement_position:
  statement_mode: default

switch_case_alignment:
  indented_cases: false

trailing_closure:
  only_single_muted_parameter: true

trailing_comma:
  mandatory_comma: false

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: false

type_contents_order:
  order:
    - associated_type
    - type_alias
    - subtype
    - case
    - type_property
    - type_method
    - ib_outlet
    - ib_inspectable
    - instance_property
    - initializer
    - ib_action
    - view_life_cycle_method
    - other_method
    - subscript

type_body_length: 200

type_name:
  min_length: 3
  max_length: 50
  validates_start_with_lowercase: true

unused_optional_binding:
  ignore_optional_try: false

vertical_whitespace:
  max_empty_lines: 1

warning_threshold: 1
